CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra

CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra

SRC = main.cpp CH_vec.cpp

main: $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o main

clean:
	rm -f main

